apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s
  name: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - image: mohamedsamir759/httpd:v1
        name: httpd
