name: ci pipline for my code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  check_source:
    name: 'Change detection on code'       
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        
  check_generated_files:
    name: 'check if generated files are up to date'
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    needs: check_source

    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5

       with:
         python-version: '3.x'

     - name: Runner image version
       run: echo "IMAGE_VERSION=${ImageVersion}" >> $GITHUB_ENV
     - name: Restore config.cache
     - uses: actions/cache@v4
       with:
         path: config.cache
         key: ${{ github.job }}-${{ runner.os }}-${{ env.IMAGE_VERSION }}-${{ needs.check_source.outputs.config_hash }}-${{ env.pythonLocation }}
