name: Kubernetes Deployment

on:

  pull_request:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

# You need to Base64 encoded your kubeconfig file before adding it in github sercrets

    - name: Setup Kubeconfig

      run: |

        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig


    - name: Apply Kubernetes configurations

      run: |

        export KUBECONFIG=kubeconfig

        kubectl apply -n k8s -f github-actions/
