name: Build and Push Docker Image

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-and-push:
    name: 'this job checkout code'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
      
  login-dockerhub: 
    name: 'this job login to dockerhub to push image'
    runs-on:  ubunnntu-latest
    steps:
      - name: Log in to Docker Hub
      - uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        env:
          REPOSITORY: nginx
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG
