
name: This is First My workflow
on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        uses: actions/checkout@v2
        run: echo "hello world"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "goodbye world"
        shell: bash
